### ISSUE TITLE
[Enhance] 크롤링 브랜드 추가

### ISSUE THREAD

**Issue by greatSumini** [pickk-dev/pickk-crawl#2]
1차 : 

- [x] 무신사m, 
- [x] 무신사공유링크, 
- [x] 배럴즈, 
- [x] 강대헌서울, 
- [x] 엄브로, 
- [x] 언더아머, 
- [x] 노스페이스, 
- [x] 에잇세컨즈, 
- [x] 퓨마, 
- [x] 휠라, 
- [x] 아디다스, 
- [x] 자라, 
- [x] 반스, 
- [x] 닥터마틴, 
- [x] 리바이스, 
- [x] 디스커버리 익스페디션, 
- [x] 내셔널지오그래픽 어패럴, 
- [x] 네이키드니스, 
- [x] 키르시, 
- [x] 던스트, 
- [x] 미나브, 
- [x] 모디파이드, 
- [x] 비욘드클로젯, 
- [x] 에두아르도

2차
- [x] 애드
- [x] 알파인더스트리
- [x] 파르티멘토
- [x] 도프제이슨
- [x] 브랜디드
- [x] 로파이
- [x] 필루미네이트
- [x] mmgl
- [x] 굿네이션(크리틱)
- [x] 이스트쿤스트
- [x] 더티셔츠뮤지엄
- [x] 집시
- [x] 어텐션로우
- [x] 니티드
- [x] 밀레클레식
- [x] 페이퍼리즘
- [x] 세인트페인
- [x] 크럼프
- [x] 오베르
- [x] 제로
- [x] 프리즘웍스
- [x] tngt
- [x] 토피
- [x] 로스트가든
- [x] 매스노운
- [x] 조셉트
- [x] 메종드스페로네
- [x] 랩101 

3차 : 
- [x] mngu, 
- [x] 아몬무브먼트, 
- [x] 르아르, 
- [x] 오디너리피플, 
- [x] 커스텀에이드, 
- [x] 컨셉원, 
- [x]  TBH SHOP(마인드브릿지, 베이직하우스, 쥬씨주디), 
- [x] 네이버스마트스토어, 
- [x] 폴로랄프로렌, 
- [x] 반츠, 
- [x] 트래블, 
- [x] 브랜슨, 
- [x] 세븐셀라, 
- [x] 지프, 
- [x] mlb, 
- [x] 야세, 
- [x] LLUD, 
- [x] 에이티브, 
- [x] 어라운드더코너, 
- [x] 하이버, 
- [x] 스타일쉐어
- [x] 트리플에이

**Comment by greatSumini** [comment]
무신사공유링크 작업 불가

**Comment by ybh1760** [comment]
2차부터 확인하면서 작업하고 있을게요!

**Comment by YYOngYYong** [comment]
퓨마

**Comment by YYOngYYong** [comment]
퓨마

**Comment by YYOngYYong** [comment]
퓨마 - 공식홈페이지 접속 불가
아이다스 - 공식홈페이지 접속 불가
