### ISSUE TITLE
크리스크리스티 최근 아우터류 크롤링이 안되어 있습니다. 

### ISSUE THREAD

**Issue by greatSumini** [pickk-dev/pickk-crawl#39]
http://chrischristy.com/product/list.html?cate_no=95

와이드라펠 더블 세미오버 코트_CHARCOAL GREY / KKMELWWDB01 등 다수

**Comment by hanqyu** [comment]
scrapy에서 ALL 카테고리를 기준으로 크롤링 하도록 수정하였습니다
