### ISSUE TITLE
알렌느 크롤링 오류

### ISSUE THREAD

**Issue by greatSumini** [pickk-dev/pickk-crawl#40]
![image](https://user-images.githubusercontent.com/48555121/92840781-7789c280-f41c-11ea-9e6e-bad7f5f56821.png)

BLACK cashmere fox mix cardigan(MT007) 제품

대표 이미지 포함 정보가 잘못 긁어와진것 같습니다

https://api.pickk.xyz/admin/items/item/16512/change/?_changelist_filters=q%3D%26brand__pk__exact%3D74

**Comment by hanqyu** [comment]
이미지 갱신하니까 해결 된거 보니까 크롤러 오류는 아닌 것 같아요!
