### ISSUE TITLE
벨리에 제품 이미지 업데이트

### ISSUE THREAD

**Issue by greatSumini** [pickk-dev/pickk-crawl#41]
https://api.pickk.xyz/admin/items/item/221/change/?_changelist_filters=q%3D%25EB%25B2%25A8%25EB%25A6%25AC%25EC%2597%2590%2B%25ED%2593%25A8%25EC%2596%25B4%2B%25EC%259A%25B8%2B%25ED%2585%258C%25EC%259D%25BC%25EB%259F%25AC%25EB%2593%259C%2B%25ED%258A%25B8%25EB%25A0%258C%25EC%25B9%2598%2B%25EC%25BD%2594%25ED%258A%25B8%2B-%2B%25EB%25A7%25A4%25ED%258A%25B8%2B%25EB%25B8%2594%25EB%259E%2599%26brand__pk__exact%3D6

제품 이미지 지난 시즌꺼 그대로 적용되어있음

**Comment by hanqyu** [comment]
현재 이미지를 자동업데이트하고 있지는 않습니다

item의 이미지 url이 s3 url로 바뀐 이후는 현재 이미지가 크롤링에서 긁어온 이미지와 다른지 여부를 판단할 수 없고, 매번 s3에 저장하기에는 부담이 크므로 그렇게 하고 있습니다. 

현재는 수동으로 업데이트 해주는 수밖에 없고(어드민의 object action 이용하면 좋음)
원래의 image url을 어딘가에 저장하고 있다가 비교하는 로직이 필요할 것 같네요
