### ISSUE TITLE
[Enhance] 크롤링 브랜드 추가2

### ISSUE THREAD

**Issue by greatSumini** [pickk-dev/pickk-crawl#5]
3.5차 :
- [x] SSG.COM
- [x] GS SHOP
- [x] 롯데백화점 공식 온라인몰
- [x] Hmall
- [x] AK MALL
- [x] 더현대닷컴
- [x] 마리오아울렛
- [x] 신세계백화점
- [x] 패션플러스
- [x] 쿠팡
- [x] 위메프
- [x] 옥션
- [x] 인터파크
- [x] G마켓
- [x] G9
- [x] 이랜드몰(키즈 제외하고 다 완료)
- [x] TNGT
- [x] 머스트잇
- [x] 매치스패션
- [x] 구찌
- [x] 서울스토어
- [x] 플레이어
- [x] 크루비
- [x] 4XR(브이투, 러기드하우스, 헤비스모커, ...)
- [x] GVG 스토어
- [x] 파페치
- [x] 아보키
- [x] 조군샵
- [x] 룩핀
- [x] 키작은남자
- [x] 맨인스토어
- [x] 타임메카
- [x] 스누브
- [x] 아이스타일24

4차 : 
- [x] 인로우스, 
- [x] 램바이디, 
- [x] 와일드브릭스, 
- [x] 상두트, 
- [x] 몬스터리퍼블릭, 
- [x] 이스트팩, 
- [x] 지오송지오, 
- [x] 탑텐몰(지오지아, 탑텐, 폴햄, 프로젝트M, ...), 
- [x] 바토즈, 
- [x] 로코베이직, 
- [x] 이올로, 
- [x] 로에일, 
- [x] 러닝노즈

5차 : 
- [x] 다이아몬드레이라, 
- [x] 네스티킥(하이퍼라운지)
- [x] 저스트새러데이, 
- [x] 아트이프액츠, 
- [x] 어널러코드, 
- [x] 라벨아카이브, 
- [x] 노앙, 
- [x] stu office, 
- [x] 크리스크리스티, 
- [x] 플루크, 
- [x] 노매뉴얼, 
- [x] 더블유브이프로젝트, 
- [x] 미니멀코드, 
- [x] 쌤소나이트, 
- [x] ETCE, 
- [x] 페플, 
- [x] 페넥, 
- [x] owl91, 
- [x] 오버더원, 
- [x] 하이츠(해브어굿타임,스투시,리차드슨,미스치프), 
- [x] 어반스터프, 
- [x] 아웃도어 프로덕츠, 
- [x] 포커페이스, 
- [x] GNCO style(티아이포맨), 
- [x] 컨츄리파우더
- [x] 슬로우애시드
- [x] 얀13
- [x] 트립션
- [x] 그루브라임
- [x] 꼼파뇨
- [x] 바스틱
- [x] 집시
- [x] 로얄라이프
- [x] 소비먼트
- [x] 트릴리온
- [x] 5252 by oioi
- [x] [프라이탁](https://www.freitag.ch/)
- [x] [제로](https://xeroxero.co.kr/index.html)
- [x] 더스토리
- [x] 하프크라이즈
- [x] 랩12
- [x] SEUNG
- [x] 브아빗
- [x] 로라로라
- [x] [리트](http://litstore.kr/)
- [x] 지플리시
- [x] 유니스디자인
- [x] 베테제
- [x] 듀테로

6차 :
- [x] 더한섬닷컴(시스템옴므), 
- [x] 닥스, 
- [x] 빈폴, 
- [x] H패션몰(타미힐피거), 
- [x] 포스333
- [x] 라코스테, 
- [x] GU, 
- [x] 프레드페리, 
- [x] 신원몰(지이크 파렌하이트,지이크, 이사베이,기니식스,아이코닉,마크엠,베스띠벨리,비키) 
- [x] MANaboveTIME, 
- [x] lfmall(해지스), 
- [x] 후아유,  
- [x] 리복, 
- [x] 오니츠카 타이거, 
- [x] 탑텐, 
- [x] 뉴에라, 
- [x] lsnmall(프로스펙스)
- [x] 네파
- [x] 스코노
- [x] 다이나핏
- [x] 23.65
- [x] 손신발
- [x] 잔스포츠
- [x] 블랙야크
- [x] 파타고니아
- [x] 탑텐
- [x] 디키즈

**Comment by ybh1760** [comment]
**3.5차 특이사항**
롯데백화점 공식 온라인몰 - 할인가를 스크립트에서 계산하는데  html파일에 수치로 나타나지 않음

**Comment by ybh1760** [comment]
5차 특이사항
1. 하이퍼라운드(네스티킥) - 아이템 상세페이지에서 아이템이미지 및 브랜드명을 가져올 수 없음

**Comment by ybh1760** [comment]
6차 특이사항
1. 닥스 - html파일에 정보가 없음

**Comment by YYOngYYong** [comment]
구찌 - alert 메세지로 인해 fetch 불가
