### ISSUE TITLE
글로즈스튜디오 크롤링 안된 제품

### ISSUE THREAD

**Issue by greatSumini** [pickk-dev/pickk-crawl#50]
http://glothes.co.kr/product/2020%EB%85%84-9%EC%9B%94-7%EC%9D%BC-%EC%9B%94%EC%9A%94%EC%9D%BC-%EC%A0%80%EB%85%81-6%EC%8B%9C-%ED%8C%90%EB%A7%A4-%EC%98%88%EC%A0%95%EC%98%A4%EB%B2%84-%EB%8D%94%EB%B8%94-%EB%B2%84%ED%8A%BC-%EC%9E%90%EC%BC%93-%EB%A9%80%ED%8B%B0%ED%94%8C-%EB%84%A4%EC%9D%B4%EB%B9%84%EC%96%BC%EB%A6%AC%EB%B2%84%EB%93%9C-%ED%95%A0%EC%9D%B8-9%EC%9B%94-%EB%A7%90%EA%B9%8C%EC%A7%80/315/category/39/display/1/

http://glothes.co.kr/product/2020%EB%85%84-9%EC%9B%94-7%EC%9D%BC-%EC%9B%94%EC%9A%94%EC%9D%BC-%EC%A0%80%EB%85%81-6%EC%8B%9C-%ED%8C%90%EB%A7%A4-%EC%98%88%EC%A0%95%EC%84%B8%EB%AF%B8-%EC%98%A4%EB%B2%84-%EC%93%B0%EB%A6%AC-%EB%B2%84%ED%8A%BC-%EC%9E%90%EC%BC%93-%EB%A9%80%ED%8B%B0%ED%94%8C-%EB%B8%8C%EB%9D%BC%EC%9A%B4%EC%96%BC%EB%A6%AC%EB%B2%84%EB%93%9C-%ED%95%A0%EC%9D%B8-9%EC%9B%94-%EB%A7%90%EA%B9%8C%EC%A7%80/314/category/39/display/1/

http://glothes.co.kr/product/2020%EB%85%84-9%EC%9B%94-7%EC%9D%BC-%EC%9B%94%EC%9A%94%EC%9D%BC-%EC%A0%80%EB%85%81-6%EC%8B%9C-%ED%8C%90%EB%A7%A4-%EC%98%88%EC%A0%95%EC%84%B8%EB%AF%B8-%EC%98%A4%EB%B2%84-%EC%93%B0%EB%A6%AC-%EB%B2%84%ED%8A%BC-%EC%9E%90%EC%BC%93-%EB%A9%80%ED%8B%B0%ED%94%8C-%EB%84%A4%EC%9D%B4%EB%B9%84%EC%96%BC%EB%A6%AC%EB%B2%84%EB%93%9C-%ED%95%A0%EC%9D%B8-9%EC%9B%94-%EB%A7%90%EA%B9%8C%EC%A7%80/313/category/39/display/1/

http://glothes.co.kr/product/2020%EB%85%84-9%EC%9B%94-7%EC%9D%BC-%EC%9B%94%EC%9A%94%EC%9D%BC-%EC%A0%80%EB%85%81-6%EC%8B%9C-%ED%8C%90%EB%A7%A4-%EC%98%88%EC%A0%95%EC%98%A4%EB%B2%84-%EB%8D%94%EB%B8%94-%EC%9E%90%EC%BC%93-%EB%A9%80%ED%8B%B0%ED%94%8C-%EB%B8%8C%EB%9D%BC%EC%9A%B4%EC%96%BC%EB%A6%AC%EB%B2%84%EB%93%9C-%ED%95%A0%EC%9D%B8-9%EC%9B%94-%EB%A7%90%EA%B9%8C%EC%A7%80/312/category/39/display/1/

http://glothes.co.kr/product/2020%EB%85%84-9%EC%9B%94-7%EC%9D%BC-%EC%9B%94%EC%9A%94%EC%9D%BC-%EC%A0%80%EB%85%81-6%EC%8B%9C-%ED%8C%90%EB%A7%A4-%EC%98%88%EC%A0%95%EC%84%B8%EB%AF%B8-%EC%99%80%EC%9D%B4%EB%93%9C-%EC%8A%AC%EB%9E%99%EC%8A%A4-%EB%A9%80%ED%8B%B0%ED%94%8C-%EB%84%A4%EC%9D%B4%EB%B9%84%EC%96%BC%EB%A6%AC%EB%B2%84%EB%93%9C-%ED%95%A0%EC%9D%B8-9%EC%9B%94-%EB%A7%90%EA%B9%8C%EC%A7%80/317/category/47/display/1/

http://glothes.co.kr/product/%EC%99%80%EC%9D%B4%EB%93%9C-%EC%8A%AC%EB%9E%99%EC%8A%A4-%EB%B2%A0%EC%9D%B4%EC%A7%80%EC%97%AC%EB%A6%84-%EA%B0%80%EB%8A%A5-%EC%9B%90%EB%8B%A8/309/category/47/display/1/

http://glothes.co.kr/product/2020%EB%85%84-9%EC%9B%94-22%EC%9D%BC-%ED%99%94%EC%9A%94%EC%9D%BC-%EC%A0%80%EB%85%81-6%EC%8B%9C-%ED%8C%90%EB%A7%A4-%EC%98%88%EC%A0%95%EC%84%B8%EB%AF%B8-%EC%99%80%EC%9D%B4%EB%93%9C-%EC%8A%AC%EB%9E%99%EC%8A%A4-%EB%8B%A4%ED%81%AC-%EA%B7%B8%EB%A0%88%EC%9D%B4%ED%81%B0-%EC%82%AC%EC%9D%B4%EC%A6%88-%EC%B6%94%EA%B0%80/163/category/47/display/1/

**Comment by hanqyu** [comment]
버그가 있었어서 이 제품들만 안들어왔네요. 수정 후 추가될 예정입니다

**Comment by hanqyu** [comment]
https://api.pickk.xyz/admin/items/item/?q=%EC%84%B8%EB%AF%B8+%EC%99%80%EC%9D%B4%EB%93%9C+%EC%8A%AC%EB%9E%99%EC%8A%A4+%EB%A9%80%ED%8B%B0%ED%94%8C+%EB%84%A4%EC%9D%B4%EB%B9%84
