### ISSUE TITLE
가먼트레이블 옵션 크롤링 502 에러

### ISSUE THREAD

**Issue by pickk-dev** [pickk-dev/pickk-crawl#52]
502: BAD_GATEWAY
Code: NO_RESPONSE_FROM_FUNCTION
아래 링크에서 위 에러가 발생합니다

https://crawl.pickk.one/api/option?url=https://garment-lable.com/product/piping-crop-slacks-khaki-gray/69/category/48/display/1/

**Comment by greatSumini** [comment]
https://garment-lable.com/product/piping-crop-slacks-khaki-gray/69/category/48/display/1/
없는 페이지네요 😅
