### ISSUE TITLE
isSoldout 키가 다른 문제

### ISSUE THREAD

**Issue by pickk-dev** [pickk-dev/pickk-crawl#53]
https://crawl.pickk.one/api/option?url=https://www.thesortie.com/all/?idx=478

https://crawl.pickk.one/api/option?url=https://haleineshop.com/product/detail.html?product_no=1444&cate_no=77&display_group=1

두 케이스가 하나는 isSoldout이고 하나는 isSoldOut인데 모두 isSoldOut으로 통일 되어야 할 듯 합니다!

**Comment by greatSumini** [comment]
ㅇㅏㅅ 원래 쓰던게 isSoldout이니 이쪽으로 통일할게용

**Comment by greatSumini** [comment]
51488b1
isSoldOut -> isSoldout, itemIsSoldOut -> itemIsSoldout 으로 모두 변경했습니다.
