### ISSUE TITLE
발루트 신규 크롤링 요청

### ISSUE THREAD

**Issue by greatSumini** [pickk-dev/pickk-crawl#54]
https://ballute.co.kr/product/soft-lambswool-crew-neck-knit-grey/962/category/154/display/1/

https://ballute.co.kr/product/soft-lambswool-crew-neck-knit-black/961/category/154/display/1/

**Comment by hanqyu** [comment]
https://api.pickk.xyz/admin/items/item/?q=SOFT+LAMBSWOOL+CREW+NECK
